version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ozmap-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: unless-stopped
    networks:
      - ozmap-network

networks:
  ozmap-network:
    driver: bridge

volumes:
  mongodb_data:
