version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ozmap-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - ozmap-network

networks:
  ozmap-network:
    driver: bridge

volumes:
  mongodb_data:
